runtime: nodejs22
service: default

# Serve files from www directory
entrypoint: serve www

# Instance configuration to prevent memory warnings
instance_class: F2  # 512MB memory (double the default F1)

# Automatic scaling configuration
automatic_scaling:
  max_instances: 10  # Limit max instances
  min_idle_instances: 1  # Keep at least 1 instance warm
  max_idle_instances: 2
  min_pending_latency: 100ms
  max_pending_latency: 500ms

handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html
    http_headers:
      Cache-Control: no-cache, no-store, must-revalidate
      Pragma: no-cache
      Expires: "0"
  - url: /(.*\.js)
    static_files: www/\1
    upload: www/.*\.js$
    http_headers:
      Cache-Control: no-cache, no-store, must-revalidate
  - url: /(.*)
    static_files: www/\1
    upload: www/(.*)

